# Generated by Django 5.1.1 on 2025-02-16 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Thoi_trang_nam', 'Thoi trang nam')], max_length=20),
        ),
    ]
