# Generated by Django 5.1.1 on 2025-02-16 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Thoi_trang_nam', 'Thoi trang nam'), ('Thoi_trang_nu', 'Thoi trang nu'), ('Dien_thoai', 'Dien thoai'), ('Me_va_be', 'Me va be')], max_length=20),
        ),
    ]
