# Generated by Django 5.1.1 on 2025-02-17 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='has_face_taker',
            field=models.BooleanField(default=False),
        ),
    ]
