# Generated by Django 5.1.1 on 2025-02-18 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_customer_has_face_taker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('AG', 'An Giang'), ('BV', 'Bà Rịa - Vũng Tàu'), ('BL', 'Bạc Liêu'), ('BK', 'Bắc Kạn'), ('BG', 'Bắc Giang'), ('BN', 'Bắc Ninh'), ('BT', 'Bến Tre'), ('BD', 'Bình Định'), ('BP', 'Bình Phước'), ('BH', 'Bình Thuận'), ('CM', 'Cà Mau'), ('CB', 'Cao Bằng'), ('CT', 'Cần Thơ'), ('DN', 'Đà Nẵng'), ('DL', 'Đắk Lắk'), ('ĐN', 'Đắk Nông'), ('DB', 'Điện Biên'), ('ĐG', 'Đồng Nai'), ('ĐT', 'Đồng Tháp'), ('GL', 'Gia Lai'), ('HG', 'Hà Giang'), ('HN', 'Hà Nội'), ('HT', 'Hà Tĩnh'), ('HD', 'Hải Dương'), ('HP', 'Hải Phòng'), ('HM', 'Hậu Giang'), ('HB', 'Hòa Bình'), ('HY', 'Hưng Yên'), ('KH', 'Khánh Hòa'), ('KG', 'Kiên Giang'), ('KT', 'Kon Tum'), ('LC', 'Lai Châu'), ('LD', 'Lâm Đồng'), ('LS', 'Lạng Sơn'), ('LĐ', 'Lào Cai'), ('LA', 'Long An'), ('ND', 'Nam Định'), ('NA', 'Nghệ An'), ('NB', 'Ninh Bình'), ('NT', 'Ninh Thuận'), ('PT', 'Phú Thọ'), ('PY', 'Phú Yên'), ('QB', 'Quảng Bình'), ('QA', 'Quảng Nam'), ('QG', 'Quảng Ngãi'), ('QN', 'Quảng Ninh'), ('QT', 'Quảng Trị'), ('ST', 'Sóc Trăng'), ('SL', 'Sơn La'), ('TH', 'Tây Ninh'), ('TB', 'Thái Bình'), ('TN', 'Thái Nguyên'), ('TH', 'Thanh Hóa'), ('TT', 'Thừa Thiên - Huế'), ('TG', 'Tiền Giang'), ('TV', 'Trà Vinh'), ('TQ', 'Tuyên Quang'), ('VL', 'Vĩnh Long'), ('VP', 'Vĩnh Phúc'), ('YB', 'Yên Bái')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Thoi_trang_nam', 'Thoi trang nam'), ('Thoi_trang_nu', 'Thoi trang nu'), ('Dien_thoai', 'Dien thoai'), ('Me_va_be', 'Me va be'), ('Thiet_bi_dien_tu', 'Thiet bi dien tu'), ('Nha_cua_doi_song', 'Nha cua doi song'), ('May_tinh_laptop', 'May tinh'), ('Sac_dep', 'Sac dep')], max_length=20),
        ),
    ]
