# Generated by Django 5.1.1 on 2025-02-19 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_customer_state_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Thoi_trang_nam', 'Thời trang nam'), ('Thoi_trang_nu', 'Thời trang nữ'), ('Dien_thoai', 'Điện thoại & phụ kiện'), ('Me_va_be', 'Mẹ & bé'), ('Thiet_bi_dien_tu', 'Thiết bị điện tử'), ('Nha_cua_doi_song', 'Nhà cửa & đời sống'), ('May_tinh_laptop', 'Máy tính & laptop'), ('Sac_dep', 'Sắc đẹp')], max_length=20),
        ),
    ]
