# Generated by Django 5.1.1 on 2025-02-19 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
