# Generated by Django 5.1.1 on 2025-02-20 02:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_wishlist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OderPlaced',
            new_name='OrderPlaced',
        ),
    ]
