# Generated by Django 5.1.1 on 2025-02-20 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_rename_oderplaced_orderplaced'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Chưa xác định', 'Chưa xác định'), ('Đã chấp nhận', 'Đã chấp nhận'), ('Đóng gói', 'Đóng gói'), ('Trên Đường Đi', 'Trên Đường Đi'), ('Đã giao hàng', 'Đã giao hàng'), ('Hủy bỏ', 'Hủy bỏ')], default='Pending', max_length=50),
        ),
    ]
