# Generated by Django 5.1.1 on 2025-02-25 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_orderplaced_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Chờ xác nhận', 'Chờ xác nhận'), ('Đã chấp nhận', 'Đã chấp nhận'), ('Đang Đóng gói', 'Đang Đóng gói'), ('Đang giao hàng', 'Đang giao hàng'), ('Đã giao hàng', 'Đã giao hàng'), ('Hủy đơn', 'Hủy đơn')], default='Chờ xác nhận', max_length=50),
        ),
    ]
